# config/secrets.yml

development:
  api_endpoints: ['http://localhost:3000/webhooks/receive', 'http://localhost:3000/webhooks/receive' ]

test:
  api_endpoints: ['http://localhost:3000/validate_webhooks/']

production:
  api_endpoint: ['https://api.example.com']
